In [ ]:
import pandas as pd
from sklearn.datasets import fetch_california_housing

# Step 2: Load the California housing dataset
housing_data = fetch_california_housing()

# Step 3: Convert to DataFrame
df = pd.DataFrame(housing_data.data, columns=housing_data.feature_names)

# Step 4: Add target variable (house prices)
df["MedHouseVal"] = housing_data.target

# Step 5: Display information of all columns
print("Dataset Information:")
print(df.info())

# Step 6: Display statistical summary of numerical columns
print("\nStatistical Summary of Numerical Columns:")
print(df.describe())

# Step 7: Simulate a categorical column ('Ocean Proximity') for analysis
df["Ocean Proximity"] = pd.cut(df["MedHouseVal"], bins=5, labels=["Near Bay", "Inland", "Island", "Near Ocean", "Ocean"])
print("\nCount of Unique Labels in 'Ocean Proximity' Column:")
print(df["Ocean Proximity"].value_counts())

# Step 8: Display columns with missing values (California dataset does not have missing values)
missing_values = df.isnull().sum()
columns_with_missing = missing_values[missing_values > 0]

print("\nColumns with Missing Values:")
print(columns_with_missing if not columns_with_missing.empty else "No missing values found")

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   MedInc       20640 non-null  float64
 1   HouseAge     20640 non-null  float64
 2   AveRooms     20640 non-null  float64
 3   AveBedrms    20640 non-null  float64
 4   Population   20640 non-null  float64
 5   AveOccup     20640 non-null  float64
 6   Latitude     20640 non-null  float64
 7   Longitude    20640 non-null  float64
 8   MedHouseVal  20640 non-null  float64
dtypes: float64(9)
memory usage: 1.4 MB
None

Statistical Summary of Numerical Columns:
             MedInc      HouseAge      AveRooms     AveBedrms    Population  \
count  20640.000000  20640.000000  20640.000000  20640.000000  20640.000000
mean       3.870671     28.639486      5.429000      1.096675   1425.476744
std        1.899822     12.585558      2.474173      0.473911   1132.462122
min        0.499900      1.000000      0.846154      0.333333      3.000000
25%        2.563400     18.000000      4.440716      1.006079    787.000000
50%        3.534800     29.000000      5.229129      1.048780   1166.000000
75%        4.743250     37.000000      6.052381      1.099526   1725.000000
max       15.000100     52.000000    141.909091     34.066667  35682.000000

           AveOccup      Latitude     Longitude   MedHouseVal
count  20640.000000  20640.000000  20640.000000  20640.000000
mean       3.070655     35.631861   -119.569704      2.068558
std       10.386050      2.135952      2.003532      1.153956
min        0.692308     32.540000   -124.350000      0.149990
25%        2.429741     33.930000   -121.800000      1.196000
50%        2.818116     34.260000   -118.490000      1.797000
75%        3.282261     37.710000   -118.010000      2.647250
max     1243.333333     41.950000   -114.310000      5.000010

Count of Unique Labels in 'Ocean Proximity' Column:
Ocean Proximity
Inland        7870
Island        4568
Near Bay      4489
Near Ocean    1991
Ocean         1722
Name: count, dtype: int64

Columns with Missing Values:
No missing values found

In [ ]:
# Step 1: Import required libraries
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import MinMaxScaler, StandardScaler

# Step 2: Load the Diabetes dataset (Ensure it's uploaded to Colab)
file_path = "/content/Dataset of Diabetes .csv"  # Update the path if needed
df = pd.read_csv(file_path)

# Step 3: Handling Missing Values (Replacing NaNs with mean)
# Create a copy of the DataFrame to avoid modifying the original DataFrame
df_numeric = df.select_dtypes(include=['number']).copy() # Select only numeric columns

# Initialize the SimpleImputer with the 'mean' strategy
imputer = SimpleImputer(strategy="mean")

# Apply the imputer to fill missing values in numeric columns only
df_numeric.iloc[:, :] = imputer.fit_transform(df_numeric)

# Merge the imputed numeric columns back into the original DataFrame
df[df_numeric.columns] = df_numeric

# Step 4: Handling Outliers (Removing values beyond 1.5*IQR)
# Calculate quartiles and IQR for numeric columns
Q1 = df_numeric.quantile(0.25) # Only compute quartiles on numeric data
Q3 = df_numeric.quantile(0.75) # Only compute quartiles on numeric data
IQR = Q3 - Q1

# Filter outliers from numeric columns and update the original DataFrame
df = df[~((df_numeric < (Q1 - 1.5 * IQR)) | (df_numeric > (Q3 + 1.5 * IQR))).any(axis=1)]

# Step 5: Data Transformation
# Min-Max Normalization (for numeric features)
min_max_scaler = MinMaxScaler()
df_minmax = pd.DataFrame(min_max_scaler.fit_transform(df_numeric), columns=df_numeric.columns) # Only transform the numeric columns

# Standardization (Z-score normalization) (for numeric features)
standard_scaler = StandardScaler()
df_standard = pd.DataFrame(standard_scaler.fit_transform(df_numeric), columns=df_numeric.columns)  # Only transform the numeric columns

# Step 6: Display Processed Data
print("\nProcessed Diabetes Dataset (Min-Max Scaled):")
print(df_minmax.head())

print("\nProcessed Diabetes Dataset (Standard Scaled):")
print(df_standard.head())

Processed Diabetes Dataset (Min-Max Scaled):
         ID  No_Pation       AGE      Urea        Cr     HbA1c      Chol  \
0  0.627034   0.000237  0.508475  0.109375  0.050378  0.264901  0.407767
1  0.918648   0.000452  0.101695  0.104167  0.070529  0.264901  0.359223
2  0.524406   0.000634  0.508475  0.109375  0.050378  0.264901  0.407767
3  0.849812   0.001160  0.508475  0.109375  0.050378  0.264901  0.407767
4  0.629537   0.000452  0.220339  0.171875  0.050378  0.264901  0.475728

         TG       HDL       LDL      VLDL       BMI
0  0.044444  0.226804  0.114583  0.011461  0.173913
1  0.081481  0.092784  0.187500  0.014327  0.139130
2  0.044444  0.226804  0.114583  0.011461  0.173913
3  0.044444  0.226804  0.114583  0.011461  0.173913
4  0.051852  0.061856  0.177083  0.008596  0.069565

Processed Diabetes Dataset (Standard Scaled):
         ID  No_Pation       AGE      Urea        Cr     HbA1c      Chol  \
0  0.672140  -0.074747 -0.401144 -0.144781 -0.382672 -1.334983 -0.509436
1  1.641852  -0.069940 -3.130017 -0.212954 -0.115804 -1.334983 -0.893730
2  0.330868  -0.065869 -0.401144 -0.144781 -0.382672 -1.334983 -0.509436
3  1.412950  -0.054126 -0.401144 -0.144781 -0.382672 -1.334983 -0.509436
4  0.680463  -0.069939 -2.334096  0.673299 -0.382672 -1.334983  0.028576

         TG       HDL       LDL      VLDL       BMI
0 -1.035084  1.810756 -1.085457 -0.369958 -1.124622
1 -0.678063 -0.158692 -0.457398 -0.342649 -1.326239
2 -1.035084  1.810756 -1.085457 -0.369958 -1.124622
3 -1.035084  1.810756 -1.085457 -0.369958 -1.124622
4 -0.963680 -0.613180 -0.547121 -0.397267 -1.729472

In [ ]:
# Step 1: Import required libraries
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import MinMaxScaler, StandardScaler, LabelEncoder

# Step 2: Load the Adult Income dataset (Ensure it's uploaded to Colab)
file_path = "/content/adult.csv.zip"  # Update the path if needed
df = pd.read_csv(file_path)

# Step 3: Handling Missing Values (Replacing '?' with NaN and imputing mode for categorical, mean for numerical)
df.replace("?", np.nan, inplace=True)

# Handling numerical missing values with mean
num_imputer = SimpleImputer(strategy="mean")
df[df.select_dtypes(include=['number']).columns] = num_imputer.fit_transform(df.select_dtypes(include=['number']))

# Handling categorical missing values with mode
cat_imputer = SimpleImputer(strategy="most_frequent")
df[df.select_dtypes(include=['object']).columns] = cat_imputer.fit_transform(df.select_dtypes(include=['object']))

# Step 4: Handling Categorical Data (Encoding)
label_encoders = {}
for col in df.select_dtypes(include=['object']).columns:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    label_encoders[col] = le

# Step 5: Handling Outliers (Removing values beyond 1.5*IQR)
Q1 = df.quantile(0.25)
Q3 = df.quantile(0.75)
IQR = Q3 - Q1
df = df[~((df < (Q1 - 1.5 * IQR)) | (df > (Q3 + 1.5 * IQR))).any(axis=1)]

# Step 6: Data Transformation
# Min-Max Normalization
min_max_scaler = MinMaxScaler()
df_minmax = pd.DataFrame(min_max_scaler.fit_transform(df), columns=df.columns)

# Standardization (Z-score normalization)
standard_scaler = StandardScaler()
df_standard = pd.DataFrame(standard_scaler.fit_transform(df), columns=df.columns)

# Step 7: Display Processed Data
print("\nProcessed Adult Income Dataset (Min-Max Scaled):")
print(df_minmax.head())

print("\nProcessed Adult Income Dataset (Standard Scaled):")
print(df_standard.head())

Processed Adult Income Dataset (Min-Max Scaled):
        age  workclass    fnlwgt  education  educational-num  marital-status  \
0  0.344262        0.0  0.188277   0.555556         0.363636        0.333333
1  0.114754        0.0  0.881156   1.000000         0.454545        0.666667
2  0.147541        0.0  0.169156   0.555556         0.363636        0.666667
3  0.672131        0.0  0.708251   0.555556         0.363636        0.333333
4  0.131148        0.0  0.475807   0.333333         0.727273        0.333333

   occupation  relationship  race  gender  capital-gain  capital-loss  \
0    0.307692           0.0   0.0     1.0           0.0           0.0
1    0.538462           0.8   0.0     0.0           0.0           0.0
2    0.000000           0.2   0.0     0.0           0.0           0.0
3    0.692308           0.0   0.0     1.0           0.0           0.0
4    0.692308           0.0   0.0     1.0           0.0           0.0

   hours-per-week  native-country  income
0        0.894737             0.0     0.0
1        0.368421             0.0     0.0
2        0.315789             0.0     0.0
3        0.105263             0.0     0.0
4        0.368421             0.0     0.0

Processed Adult Income Dataset (Standard Scaled):
        age  workclass    fnlwgt  education  educational-num  marital-status  \
0  0.220179        0.0 -1.022983  -0.151256        -0.654083       -0.398228
1 -0.955630        0.0  2.234629   1.457372        -0.073261        0.828047
2 -0.787657        0.0 -1.112882  -0.151256        -0.654083        0.828047
3  1.899906        0.0  1.421707  -0.151256        -0.654083       -0.398228
4 -0.871644        0.0  0.328856  -0.955571         1.669207       -0.398228

   occupation  relationship  race    gender  capital-gain  capital-loss  \
0   -0.420679     -1.044582   0.0  0.770972           0.0           0.0
1    0.305840      1.629927   0.0 -1.297064           0.0           0.0
2   -1.389371     -0.375955   0.0 -1.297064           0.0           0.0
3    0.790186     -1.044582   0.0  0.770972           0.0           0.0
4    0.790186     -1.044582   0.0  0.770972           0.0           0.0

   hours-per-week  native-country  income
0        2.312838             0.0     0.0
1       -0.329781             0.0     0.0
2       -0.594043             0.0     0.0
3       -1.651090             0.0     0.0
4       -0.329781             0.0     0.0

In [ ]:
import pandas as pd

df = pd.read_csv("house.csv")
print("Information of all columns:")
print(df.info())


print("\nStatistical information of numerical columns:")
print(df.describe())

# count of unique labels for the Ocean Proximity column
print("\nCount of unique labels in 'Ocean Proximity' column:")
print(df['ocean_proximity'].value_counts())

# Display attributes with missing values count greater than zero
print("\nAttributes with missing values:")
missing_values = df.isnull().sum()
missing_columns = missing_values[missing_values > 0]
print(missing_columns)

Information of all columns:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object
dtypes: float64(9), object(1)
memory usage: 1.6+ MB
None

Statistical information of numerical columns:
          longitude      latitude  housing_median_age   total_rooms  \
count  20640.000000  20640.000000        20640.000000  20640.000000
mean    -119.569704     35.631861           28.639486   2635.763081
std        2.003532      2.135952           12.585558   2181.615252
min     -124.350000     32.540000            1.000000      2.000000
25%     -121.800000     33.930000           18.000000   1447.750000
50%     -118.490000     34.260000           29.000000   2127.000000
75%     -118.010000     37.710000           37.000000   3148.000000
max     -114.310000     41.950000           52.000000  39320.000000

       total_bedrooms    population    households  median_income  \
count    20433.000000  20640.000000  20640.000000   20640.000000
mean       537.870553   1425.476744    499.539680       3.870671
std        421.385070   1132.462122    382.329753       1.899822
min          1.000000      3.000000      1.000000       0.499900
25%        296.000000    787.000000    280.000000       2.563400
50%        435.000000   1166.000000    409.000000       3.534800
75%        647.000000   1725.000000    605.000000       4.743250
max       6445.000000  35682.000000   6082.000000      15.000100

       median_house_value
count        20640.000000
mean        206855.816909
std         115395.615874
min          14999.000000
25%         119600.000000
50%         179700.000000
75%         264725.000000
max         500001.000000

Count of unique labels in 'Ocean Proximity' column:
ocean_proximity
<1H OCEAN     9136
INLAND        6551
NEAR OCEAN    2658
NEAR BAY      2290
ISLAND           5
Name: count, dtype: int64

Attributes with missing values:
total_bedrooms    207
dtype: int64